#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Examine;
    
    #line 3 "..\..\Views\Partials\Grid\Fanoe.cshtml"
    using Newtonsoft.Json.Linq;
    
    #line default
    #line hidden
    using umbraco;
    using Umbraco.Core;
    using Umbraco.Core.Models;
    using Umbraco.Web;
    using Umbraco.Web.Mvc;
    using Umbraco.Web.PublishedContentModels;
    
    #line 2 "..\..\Views\Partials\Grid\Fanoe.cshtml"
    using Umbraco.Web.Templates;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Partials/Grid/Fanoe.cshtml")]
    public partial class _Views_Partials_Grid_Fanoe_cshtml : UmbracoViewPage<dynamic>
    {

#line 43 "..\..\Views\Partials\Grid\Fanoe.cshtml"
public System.Web.WebPages.HelperResult renderRow(dynamic row, bool singleColumn)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 44 "..\..\Views\Partials\Grid\Fanoe.cshtml"
 


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <div ");


#line 45 "..\..\Views\Partials\Grid\Fanoe.cshtml"
WriteTo(__razor_helper_writer, RenderElementAttributes(row));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, ">\n");

WriteLiteralTo(__razor_helper_writer, "        ");


#line 46 "..\..\Views\Partials\Grid\Fanoe.cshtml"
WriteTo(__razor_helper_writer, Umbraco.If(singleColumn, "<div class='container'>"));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\n        <div");

WriteLiteralTo(__razor_helper_writer, " class=\"row clearfix\"");

WriteLiteralTo(__razor_helper_writer, ">\n");


#line 48 "..\..\Views\Partials\Grid\Fanoe.cshtml"
            

#line default
#line hidden

#line 48 "..\..\Views\Partials\Grid\Fanoe.cshtml"
             foreach ( var area in row.areas ) {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "            <div");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 1417), Tuple.Create("\"", 1449)
, Tuple.Create(Tuple.Create("", 1425), Tuple.Create("col-md-", 1425), true)

#line 49 "..\..\Views\Partials\Grid\Fanoe.cshtml"
, Tuple.Create(Tuple.Create("", 1432), Tuple.Create<System.Object, System.Int32>(area.grid

#line default
#line hidden
, 1432), false)
, Tuple.Create(Tuple.Create(" ", 1442), Tuple.Create("column", 1443), true)
);

WriteLiteralTo(__razor_helper_writer, ">\n                <div ");


#line 50 "..\..\Views\Partials\Grid\Fanoe.cshtml"
WriteTo(__razor_helper_writer, RenderElementAttributes(area));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, ">\n");


#line 51 "..\..\Views\Partials\Grid\Fanoe.cshtml"
                    

#line default
#line hidden

#line 51 "..\..\Views\Partials\Grid\Fanoe.cshtml"
                     foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                            ");


#line 53 "..\..\Views\Partials\Grid\Fanoe.cshtml"
    WriteTo(__razor_helper_writer, Html.Partial("grid/editors/base", (object)control));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\n");


#line 54 "..\..\Views\Partials\Grid\Fanoe.cshtml"
                        }
                    }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                </div>\n            </div>");


#line 57 "..\..\Views\Partials\Grid\Fanoe.cshtml"
                  }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        </div>\n");

WriteLiteralTo(__razor_helper_writer, "        ");


#line 59 "..\..\Views\Partials\Grid\Fanoe.cshtml"
WriteTo(__razor_helper_writer, Umbraco.If(singleColumn, "</div>"));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\n    </div>\n");


#line 61 "..\..\Views\Partials\Grid\Fanoe.cshtml"


#line default
#line hidden
});

#line 61 "..\..\Views\Partials\Grid\Fanoe.cshtml"
}
#line default
#line hidden

        #line 64 "..\..\Views\Partials\Grid\Fanoe.cshtml"
 
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

		if(cfg != null) 
		{
            foreach (JProperty property in cfg.Properties()) 
			{
                attrs.Add(property.Name + "='" + property.Value.ToString() + "'");
            }
		}
		
        JObject style = contentItem.styles;

        if (style != null) 
		{ 
        	var cssVals = new List<string>();
			foreach (JProperty property in style.Properties()) 
			{
            	cssVals.Add(property.Name + ":" + property.Value.ToString() + ";");
			}

			if (cssVals.Any()) 
			{
            	attrs.Add("style='" + string.Join(" ", cssVals) + "'");
			}
        }
            
        return new MvcHtmlString(string.Join(" ", attrs));
    }

        #line default
        #line hidden
        
        public _Views_Partials_Grid_Fanoe_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\n");

            
            #line 5 "..\..\Views\Partials\Grid\Fanoe.cshtml"
 if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"umb-grid\"");

WriteLiteral(">\n");

            
            #line 10 "..\..\Views\Partials\Grid\Fanoe.cshtml"
        
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Partials\Grid\Fanoe.cshtml"
         if (oneColumn)
        {
            foreach (var section in Model.sections) 
			{

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"grid-section\"");

WriteLiteral(">\n");

            
            #line 15 "..\..\Views\Partials\Grid\Fanoe.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Partials\Grid\Fanoe.cshtml"
                     foreach (var row in section.rows) 
					{
                        
            
            #line default
            #line hidden
            
            #line 17 "..\..\Views\Partials\Grid\Fanoe.cshtml"
                   Write(renderRow(row, true));

            
            #line default
            #line hidden
            
            #line 17 "..\..\Views\Partials\Grid\Fanoe.cshtml"
                                             ;
                    }

            
            #line default
            #line hidden
WriteLiteral("                </div>\n");

            
            #line 20 "..\..\Views\Partials\Grid\Fanoe.cshtml"
            }   
        }
		else 
		{ 

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\n                <div");

WriteLiteral(" class=\"row clearfix\"");

WriteLiteral(">\n");

            
            #line 26 "..\..\Views\Partials\Grid\Fanoe.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\Partials\Grid\Fanoe.cshtml"
                     foreach (var s in Model.sections) 
					{

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"grid-section\"");

WriteLiteral(">\n                            <div");

WriteAttribute("class", Tuple.Create(" class=\"", 809), Tuple.Create("\"", 838)
, Tuple.Create(Tuple.Create("", 817), Tuple.Create("col-md-", 817), true)
            
            #line 29 "..\..\Views\Partials\Grid\Fanoe.cshtml"
, Tuple.Create(Tuple.Create("", 824), Tuple.Create<System.Object, System.Int32>(s.grid
            
            #line default
            #line hidden
, 824), false)
, Tuple.Create(Tuple.Create(" ", 831), Tuple.Create("column", 832), true)
);

WriteLiteral(">\n");

            
            #line 30 "..\..\Views\Partials\Grid\Fanoe.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\Partials\Grid\Fanoe.cshtml"
                                 foreach (var row in s.rows) 
								{
                                    
            
            #line default
            #line hidden
            
            #line 32 "..\..\Views\Partials\Grid\Fanoe.cshtml"
                               Write(renderRow(row, false));

            
            #line default
            #line hidden
            
            #line 32 "..\..\Views\Partials\Grid\Fanoe.cshtml"
                                                          ;
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </div>\n                        </div>\n");

            
            #line 36 "..\..\Views\Partials\Grid\Fanoe.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </div>\n            </div>   \n");

            
            #line 39 "..\..\Views\Partials\Grid\Fanoe.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\n");

            
            #line 41 "..\..\Views\Partials\Grid\Fanoe.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("\n");

        }
    }
}
#pragma warning restore 1591
